spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_system_db
    username: booking_admin
    password: booking_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

app:
  jwt:
    secret: o8akM9FgBfNDf+H3cmFj5PI82DTAGlqJoXVTOeCvQs4=
    expiration-ms: 3600000
