spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_fresh?useSSL=false&serverTimezone=UTC
    username: booking_admin    
    password: Str0ngP@ssw0rd123!  
  jpa:
    hibernate:
      ddl-auto: update         
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwt:
    secret: change-me-to-a-strong-secret-at-least-256-bit
    expiration-ms: 3600000 

server:
  port: 8080
